openapi: 3.0.3
info:
  title: PA Service API
  description: |
    ICAO Passive Authentication Service API.
    Dedicated service for ICAO 9303 Passive Authentication verification.

    ## Changelog
    - **v2.1.4** (2026-02-14): DSC Non-Conformant status fields (dscNonConformant, pkdConformanceCode, pkdConformanceText)
    - **v2.1.3** (2026-02-14): Lightweight PA Lookup API (POST /api/certificates/pa-lookup)
    - **v2.1.2** (2026-02-13): CRL expiration check, crlThisUpdate/crlNextUpdate fields, CRL_EXPIRED status
    - **v2.1.1** (2026-02-12): DSC auto-registration from PA verify, DG2 JPEG2000→JPEG conversion
    - **v1.2.0** (2026-01-06): Certificate expiration fields
    - **v1.1.0** (2026-01-03): API Gateway integration
    - **v1.0.0** (2025-12-30): Initial release
  version: 2.1.4
  contact:
    name: SmartCore Inc.
    email: support@smartcoreinc.com

servers:
  - url: http://localhost:8082
    description: Development server (direct)
  - url: http://localhost:8080
    description: API Gateway (prefix /api/pa)

tags:
  - name: Health
    description: Health check endpoints
  - name: PA
    description: Passive Authentication verification
  - name: Parser
    description: Document parsing utilities (SOD, DG1, DG2, MRZ)

paths:
  # ============================================
  # Health Endpoints
  # ============================================
  /api/health:
    get:
      tags: [Health]
      summary: Application health check
      operationId: getHealth
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

  /api/health/database:
    get:
      tags: [Health]
      summary: Database health check
      operationId: getDatabaseHealth
      responses:
        '200':
          description: Database connection status

  /api/health/ldap:
    get:
      tags: [Health]
      summary: LDAP health check
      operationId: getLdapHealth
      responses:
        '200':
          description: LDAP connection status

  # ============================================
  # PA Verification
  # ============================================
  /api/pa/verify:
    post:
      tags: [PA]
      summary: Verify Passive Authentication
      description: |
        Perform ICAO 9303 Passive Authentication verification (8-step process).

        **Steps**: SOD Parse → DSC Extract → DSC Trust Chain → CSCA Lookup →
        SOD Signature → DG Hash → CRL Check (expiration + revocation) → Result

        **DSC Auto-Registration**: If the DSC is not in the local PKD, it is automatically
        registered with source_type='PA_EXTRACTED'.

        **Response includes**: verification steps, document info, face image (JPEG),
        verification timestamp, processing duration.
      operationId: verifyPA
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PAVerifyRequest'
      responses:
        '200':
          description: Verification result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PAVerifyResponse'
        '400':
          description: Invalid request

  /api/pa/history:
    get:
      tags: [PA]
      summary: Get PA verification history
      operationId: getPAHistory
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: PA history list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PAHistoryResponse'

  /api/pa/{id}:
    get:
      tags: [PA]
      summary: Get verification detail
      operationId: getPADetail
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Verification detail
        '404':
          description: Not found

  /api/pa/{id}/datagroups:
    get:
      tags: [PA]
      summary: Get DataGroups detail
      description: Returns parsed DataGroup information including DG2 face image (JPEG).
      operationId: getPADataGroups
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: DataGroups detail with face image
        '404':
          description: Not found

  /api/pa/statistics:
    get:
      tags: [PA]
      summary: Get PA statistics
      operationId: getPAStatistics
      responses:
        '200':
          description: PA statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PAStatisticsResponse'

  # ============================================
  # Document Parsing Utilities
  # ============================================
  /api/pa/parse-sod:
    post:
      tags: [Parser]
      summary: Parse SOD (Security Object Document)
      description: Parse an ICAO 9303 SOD and extract metadata, hash algorithm, DG hashes.
      operationId: parseSOD
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sod:
                  type: string
                  description: Base64 encoded SOD
              required: [sod]
      responses:
        '200':
          description: Parsed SOD data

  /api/pa/parse-dg1:
    post:
      tags: [Parser]
      summary: Parse DG1 (MRZ data)
      description: Parse DG1 DataGroup and extract MRZ fields.
      operationId: parseDG1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dg1:
                  type: string
                  description: Base64 encoded DG1
              required: [dg1]
      responses:
        '200':
          description: Parsed MRZ data

  /api/pa/parse-dg2:
    post:
      tags: [Parser]
      summary: Parse DG2 (Face image)
      description: |
        Parse DG2 DataGroup and extract face image.
        JPEG2000 images are automatically converted to JPEG for browser compatibility.
      operationId: parseDG2
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dg2:
                  type: string
                  description: Base64 encoded DG2
              required: [dg2]
      responses:
        '200':
          description: Face image data (JPEG base64)

  /api/pa/parse-mrz-text:
    post:
      tags: [Parser]
      summary: Parse MRZ text
      description: Parse raw MRZ text and extract fields (document type, name, nationality, etc.)
      operationId: parseMRZText
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mrz:
                  type: string
                  description: Raw MRZ text (2 or 3 lines)
              required: [mrz]
      responses:
        '200':
          description: Parsed MRZ fields

components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: UP
        service:
          type: string
          example: pa-service
        version:
          type: string
          example: 2.1.4
        timestamp:
          type: string

    PAVerifyRequest:
      type: object
      required: [sod, dataGroups]
      properties:
        sod:
          type: string
          description: Base64 encoded SOD (Security Object Document)
        dataGroups:
          type: object
          additionalProperties:
            type: string
          description: Map of DG number to Base64 encoded data (e.g., {"1":"...", "2":"..."})
        mrzData:
          type: string
          description: Optional MRZ data for additional validation

    PAVerifyResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            verificationId:
              type: string
              format: uuid
            status:
              type: string
              enum: [VALID, INVALID]
            verificationTimestamp:
              type: string
              format: date-time
            processingDurationMs:
              type: integer
            issuingCountry:
              type: string
            documentNumber:
              type: string
            certificateChainValidation:
              $ref: '#/components/schemas/CertificateChainValidation'
            sodSignatureValidation:
              type: object
              properties:
                valid:
                  type: boolean
                hashAlgorithm:
                  type: string
                signatureAlgorithm:
                  type: string
                algorithm:
                  type: string
            dataGroupValidation:
              type: object
              properties:
                totalGroups:
                  type: integer
                validGroups:
                  type: integer
                invalidGroups:
                  type: integer
                details:
                  type: object
                  additionalProperties:
                    type: object
                    properties:
                      valid:
                        type: boolean
                      expectedHash:
                        type: string
                      actualHash:
                        type: string
            dscAutoRegistration:
              $ref: '#/components/schemas/DscAutoRegistration'

    CertificateChainValidation:
      type: object
      properties:
        valid:
          type: boolean
          description: Trust chain verification result
        message:
          type: string
          description: Error message (on failure)
        dscSubject:
          type: string
          description: DSC certificate Subject DN
        dscSerialNumber:
          type: string
          description: DSC certificate serial number
        cscaSubject:
          type: string
          description: CSCA certificate Subject DN
        cscaFingerprint:
          type: string
          description: CSCA certificate SHA-256 fingerprint
        countryCode:
          type: string
          description: Country code extracted from DSC
        notBefore:
          type: string
          description: DSC certificate validity start (ISO 8601)
        notAfter:
          type: string
          description: DSC certificate validity end (ISO 8601)
        crlStatus:
          type: string
          enum: [NOT_REVOKED, REVOKED, CRL_EXPIRED, UNKNOWN]
          description: "CRL status: NOT_REVOKED, REVOKED, CRL_EXPIRED (nextUpdate passed), UNKNOWN"
        crlThisUpdate:
          type: string
          description: CRL issue date (ISO 8601, e.g. 2026-02-01T00:00:00)
        crlNextUpdate:
          type: string
          description: CRL next update date (ISO 8601, e.g. 2026-03-01T00:00:00)
        dscExpired:
          type: boolean
          description: Whether DSC certificate is expired
        cscaExpired:
          type: boolean
          description: Whether CSCA certificate is expired
        validAtSigningTime:
          type: boolean
          description: Whether certificate was valid at passport signing time (ICAO 9303 Point-in-Time)
        expirationStatus:
          type: string
          enum: [VALID, WARNING, EXPIRED]
        expirationMessage:
          type: string
        dscNonConformant:
          type: boolean
          description: "true if DSC is ICAO PKD Non-Conformant (only included when true)"
        pkdConformanceCode:
          type: string
          description: "ICAO PKD non-conformance reason code (e.g., ERR:CSCA.CDP.14). Only included when dscNonConformant=true"
        pkdConformanceText:
          type: string
          description: "ICAO PKD non-conformance reason description. Only included when dscNonConformant=true"

    DscAutoRegistration:
      type: object
      description: DSC auto-registration result (included only when registration attempted)
      properties:
        registered:
          type: boolean
        newlyRegistered:
          type: boolean
          description: "true: newly registered, false: already existed"
        certificateId:
          type: string
          format: uuid
        fingerprint:
          type: string
          description: DSC SHA-256 fingerprint (hex, 64 chars)
        countryCode:
          type: string

    PAVerificationStep:
      type: object
      properties:
        step:
          type: integer
        name:
          type: string
        status:
          type: string
          enum: [passed, failed, skipped]
        message:
          type: string
        failureReason:
          type: string

    PAStatisticsResponse:
      type: object
      properties:
        totalVerifications:
          type: integer
        successRate:
          type: number
          format: float
        byCountry:
          type: array
          items:
            type: object
            properties:
              country:
                type: string
              count:
                type: integer
        byStatus:
          type: object
          properties:
            VALID:
              type: integer
            INVALID:
              type: integer

    PAHistoryResponse:
      type: object
      properties:
        total:
          type: integer
        items:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                format: uuid
              verifiedAt:
                type: string
                format: date-time
              issuingCountry:
                type: string
              documentType:
                type: string
              status:
                type: string
                enum: [VALID, INVALID]
              processingDurationMs:
                type: integer
