openapi: 3.0.3
info:
  title: Sync Service API
  description: |
    DB-LDAP Synchronization and Certificate Re-validation Service API.
    Monitors synchronization between PostgreSQL and OpenLDAP, and performs
    certificate expiration re-validation.

    ## Changelog
    - **v1.6.0** (2026-01-14): Auto Reconcile feature complete (Phase 1-6)
    - **v1.2.0** (2026-01-07): Remove interval sync, keep only daily scheduler
    - **v1.1.0** (2026-01-06): Daily scheduler at midnight, certificate re-validation
    - **v1.0.0** (2026-01-03): Initial release
  version: 1.6.0
  contact:
    name: SmartCore Inc.
    email: support@smartcoreinc.com

servers:
  - url: http://localhost:8083
    description: Development server
  - url: http://sync-service:8083
    description: Docker internal

tags:
  - name: Health
    description: Health check endpoints
  - name: Sync
    description: Synchronization operations
  - name: Reconcile
    description: Auto reconciliation operations
  - name: Revalidation
    description: Certificate re-validation operations
  - name: Config
    description: Configuration endpoints

paths:
  /api/sync/health:
    get:
      tags: [Health]
      summary: Service health check
      description: Returns the health status of the sync service
      operationId: getHealth
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

  /api/sync/status:
    get:
      tags: [Sync]
      summary: Get sync status
      description: Returns current synchronization status with DB and LDAP statistics
      operationId: getSyncStatus
      responses:
        '200':
          description: Sync status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyncStatusResponse'

  /api/sync/check:
    post:
      tags: [Sync]
      summary: Check sync status
      description: Trigger a sync status check
      operationId: checkSync
      responses:
        '200':
          description: Check completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyncCheckResponse'

  /api/sync/discrepancies:
    get:
      tags: [Sync]
      summary: Get discrepancies
      description: Returns list of discrepancies between DB and LDAP
      operationId: getDiscrepancies
      parameters:
        - name: type
          in: query
          schema:
            type: string
            enum: [all, missing_in_ldap, missing_in_db, mismatch]
          description: Filter by discrepancy type
        - name: limit
          in: query
          schema:
            type: integer
            default: 100
      responses:
        '200':
          description: Discrepancy list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiscrepanciesResponse'

  /api/sync/reconcile:
    post:
      tags: [Reconcile]
      summary: Reconcile discrepancies
      description: |
        Trigger auto reconciliation to fix DB-LDAP discrepancies (v1.6.0+).

        **Features**:
        - Modular ReconciliationEngine architecture
        - Batch processing (default: 100 certificates)
        - Database logging (reconciliation_summary, reconciliation_log)
        - Dry-run mode support
        - Integrated with daily scheduler

        **Workflow**:
        1. Identify missing certificates in LDAP
        2. Add certificates in batches
        3. Log each operation
        4. Update summary with final results
      operationId: reconcile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReconcileRequest'
      responses:
        '200':
          description: Reconciliation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReconcileResponse'

  /api/sync/reconcile/history:
    get:
      tags: [Reconcile]
      summary: Get reconciliation history
      description: |
        Get history of auto reconciliation executions with pagination (v1.6.0+).

        **Filtering**:
        - By status (COMPLETED, FAILED, PARTIAL, IN_PROGRESS)
        - By trigger type (MANUAL, AUTO, DAILY_SYNC)
      operationId: getReconcileHistory
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
          description: Maximum number of records
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
            minimum: 0
          description: Number of records to skip
        - name: status
          in: query
          schema:
            type: string
            enum: [COMPLETED, FAILED, PARTIAL, IN_PROGRESS]
          description: Filter by status
        - name: triggeredBy
          in: query
          schema:
            type: string
            enum: [MANUAL, AUTO, DAILY_SYNC]
          description: Filter by trigger type
      responses:
        '200':
          description: Reconciliation history
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReconcileHistoryResponse'

  /api/sync/reconcile/{id}:
    get:
      tags: [Reconcile]
      summary: Get reconciliation details
      description: |
        Get detailed information for a specific reconciliation execution (v1.6.0+).

        **Includes**:
        - Summary (status, trigger, counts, duration)
        - Operation logs (all individual certificate operations)
        - Per-operation timing and status
      operationId: getReconcileDetails
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Reconciliation summary ID
      responses:
        '200':
          description: Reconciliation details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReconcileDetailResponse'
        '404':
          description: Reconciliation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/sync/history:
    get:
      tags: [Sync]
      summary: Get sync history
      description: Returns history of sync operations
      operationId: getSyncHistory
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Sync history
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyncHistoryResponse'

  /api/sync/config:
    get:
      tags: [Config]
      summary: Get configuration
      description: Returns current sync service configuration
      operationId: getConfig
      responses:
        '200':
          description: Configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigResponse'

  /api/sync/revalidate:
    post:
      tags: [Revalidation]
      summary: Trigger certificate re-validation
      description: |
        Re-check all certificates for expiration and update validation status.
        This checks the `not_after` field against current time and updates
        `is_expired` and `validation_status` fields in validation_result table.
      operationId: revalidateCertificates
      responses:
        '200':
          description: Re-validation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RevalidationResult'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/sync/revalidation-history:
    get:
      tags: [Revalidation]
      summary: Get re-validation history
      description: Returns history of certificate re-validation operations
      operationId: getRevalidationHistory
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
          description: Maximum number of records to return
      responses:
        '200':
          description: Re-validation history
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RevalidationHistoryItem'

  /api/sync/trigger-daily:
    post:
      tags: [Sync]
      summary: Trigger daily sync manually
      description: |
        Manually trigger the daily sync process which includes:
        1. Sync check (DB-LDAP comparison)
        2. Certificate re-validation (if enabled)
      operationId: triggerDailySync
      responses:
        '200':
          description: Daily sync triggered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TriggerResponse'

components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          enum: [healthy, unhealthy, degraded]
        service:
          type: string
        version:
          type: string
        timestamp:
          type: string
          format: date-time
        components:
          type: object
          properties:
            database:
              type: string
              enum: [connected, disconnected]
            ldap:
              type: string
              enum: [connected, disconnected]

    SyncStatusResponse:
      type: object
      properties:
        syncStatus:
          type: string
          enum: [synced, out_of_sync, unknown]
        lastSyncTime:
          type: string
          format: date-time
        lastCheckTime:
          type: string
          format: date-time
        dbStats:
          $ref: '#/components/schemas/DBStats'
        ldapStats:
          $ref: '#/components/schemas/LDAPStats'
        discrepancyCount:
          type: integer

    DBStats:
      type: object
      properties:
        totalCertificates:
          type: integer
        csca:
          type: integer
        dsc:
          type: integer
        dscNc:
          type: integer
        crl:
          type: integer
        masterList:
          type: integer
        countries:
          type: integer

    LDAPStats:
      type: object
      properties:
        totalEntries:
          type: integer
        csca:
          type: integer
        dsc:
          type: integer
        dscNc:
          type: integer
        crl:
          type: integer
        masterList:
          type: integer
        countries:
          type: integer

    SyncCheckResponse:
      type: object
      properties:
        success:
          type: boolean
        checkTime:
          type: string
          format: date-time
        syncStatus:
          type: string
        discrepanciesFound:
          type: integer
        message:
          type: string

    DiscrepanciesResponse:
      type: object
      properties:
        total:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/Discrepancy'

    Discrepancy:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
          enum: [missing_in_ldap, missing_in_db, mismatch]
        certificateType:
          type: string
          enum: [CSCA, DSC, DSC_NC, CRL, ML]
        countryCode:
          type: string
        serialNumber:
          type: string
        subject:
          type: string
        detectedAt:
          type: string
          format: date-time
        details:
          type: string

    ReconcileRequest:
      type: object
      properties:
        mode:
          type: string
          enum: [auto, db_to_ldap, ldap_to_db]
          default: auto
          description: |
            Reconciliation mode:
            - auto: Automatically determine the correct action
            - db_to_ldap: Copy missing entries from DB to LDAP
            - ldap_to_db: Copy missing entries from LDAP to DB
        discrepancyIds:
          type: array
          items:
            type: string
          description: Specific discrepancy IDs to reconcile (empty = all)
        dryRun:
          type: boolean
          default: false
          description: If true, only simulate the reconciliation

    ReconcileResponse:
      type: object
      properties:
        success:
          type: boolean
        mode:
          type: string
        dryRun:
          type: boolean
        processed:
          type: integer
        fixed:
          type: integer
        failed:
          type: integer
        details:
          type: array
          items:
            $ref: '#/components/schemas/ReconcileDetail'

    ReconcileDetail:
      type: object
      properties:
        discrepancyId:
          type: string
        action:
          type: string
        status:
          type: string
          enum: [success, failed, skipped]
        message:
          type: string

    SyncHistoryResponse:
      type: object
      properties:
        total:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/SyncHistoryItem'

    SyncHistoryItem:
      type: object
      properties:
        id:
          type: string
        timestamp:
          type: string
          format: date-time
        type:
          type: string
          enum: [check, reconcile, manual]
        status:
          type: string
          enum: [success, partial, failed]
        discrepanciesFound:
          type: integer
        discrepanciesFixed:
          type: integer
        duration:
          type: integer
          description: Duration in milliseconds
        triggeredBy:
          type: string
          enum: [scheduler, manual, api]

    ConfigResponse:
      type: object
      properties:
        autoReconcile:
          type: boolean
          description: Whether to automatically reconcile discrepancies
        maxReconcileBatchSize:
          type: integer
          description: Maximum number of entries to reconcile per batch
        dailySyncEnabled:
          type: boolean
          description: Whether daily sync at scheduled time is enabled
        dailySyncTime:
          type: string
          description: Scheduled time for daily sync in HH:MM format
          example: "00:00"
        revalidateCertsOnSync:
          type: boolean
          description: Whether to re-validate certificates during daily sync
        dbConfig:
          type: object
          properties:
            host:
              type: string
            port:
              type: integer
            database:
              type: string
        ldapConfig:
          type: object
          properties:
            readHost:
              type: string
            readPort:
              type: integer
            writeHost:
              type: string
            writePort:
              type: integer
            baseDn:
              type: string

    RevalidationResult:
      type: object
      description: Result of certificate re-validation operation (v1.1.0+)
      properties:
        success:
          type: boolean
          description: Whether the operation completed successfully
        totalProcessed:
          type: integer
          description: Total number of certificates processed
        newlyExpired:
          type: integer
          description: Number of certificates newly marked as expired
        newlyValid:
          type: integer
          description: Number of certificates that became valid again
        unchanged:
          type: integer
          description: Number of certificates with no status change
        errors:
          type: integer
          description: Number of processing errors
        durationMs:
          type: integer
          description: Duration of the operation in milliseconds

    RevalidationHistoryItem:
      type: object
      description: A record from re-validation history (v1.1.0+)
      properties:
        id:
          type: integer
          description: Record ID
        executedAt:
          type: string
          format: date-time
          description: When the re-validation was executed
        totalProcessed:
          type: integer
        newlyExpired:
          type: integer
        newlyValid:
          type: integer
        unchanged:
          type: integer
        errors:
          type: integer
        durationMs:
          type: integer

    TriggerResponse:
      type: object
      description: Response for manual trigger operations
      properties:
        success:
          type: boolean
        message:
          type: string
          description: Status message

    ReconcileHistoryResponse:
      type: object
      description: Reconciliation history list (v1.6.0+)
      properties:
        total:
          type: integer
        limit:
          type: integer
        offset:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/ReconcileHistoryItem'

    ReconcileHistoryItem:
      type: object
      description: Single reconciliation execution summary (v1.6.0+)
      properties:
        id:
          type: integer
        startedAt:
          type: string
          format: date-time
        completedAt:
          type: string
          format: date-time
        status:
          type: string
          enum: [COMPLETED, FAILED, PARTIAL, IN_PROGRESS]
        triggeredBy:
          type: string
          enum: [MANUAL, AUTO, DAILY_SYNC]
        totalProcessed:
          type: integer
        successCount:
          type: integer
        failureCount:
          type: integer
        cscaAdded:
          type: integer
        dscAdded:
          type: integer
        dscNcAdded:
          type: integer
        durationMs:
          type: integer

    ReconcileDetailResponse:
      type: object
      description: Detailed reconciliation execution information (v1.6.0+)
      properties:
        success:
          type: boolean
        summary:
          $ref: '#/components/schemas/ReconcileHistoryItem'
        operations:
          type: array
          items:
            $ref: '#/components/schemas/ReconcileOperationLog'

    ReconcileOperationLog:
      type: object
      description: Individual certificate reconciliation operation (v1.6.0+)
      properties:
        id:
          type: integer
        operation:
          type: string
          enum: [ADD_CERT_TO_LDAP, DELETE_CERT_FROM_LDAP]
        certType:
          type: string
          enum: [CSCA, DSC, DSC_NC, CRL, ML]
        countryCode:
          type: string
        subject:
          type: string
        serialNumber:
          type: string
        status:
          type: string
          enum: [SUCCESS, FAILED]
        errorMessage:
          type: string
        operationTimestampMs:
          type: integer
          description: Operation timestamp in milliseconds

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          default: false
        error:
          type: string
          description: Error message
