export { Dashboard } from './Dashboard';
export { FileUpload } from './FileUpload';
export { UploadHistory } from './UploadHistory';
export { UploadDetail } from './UploadDetail';
export { UploadDashboard } from './UploadDashboard';
export { PAVerify } from './PAVerify';
export { PAHistory } from './PAHistory';
export { PADetail } from './PADetail';
export { PADashboard } from './PADashboard';
export { SyncDashboard } from './SyncDashboard';
export { default as APIDocs } from './APIDocs';
