-- =============================================================================
-- Fix certificate_duplicates table schema to match PostgreSQL
-- =============================================================================
-- Issue: Oracle schema has different columns than PostgreSQL
-- PostgreSQL: certificate_id, upload_id, source_type, source_country, source_entry_dn, source_file_name, detected_at
-- Oracle (OLD): fingerprint_sha256, certificate_type, subject_dn, issuer_dn, serial_number, first_upload_id, etc.
-- This script migrates Oracle to match PostgreSQL schema
-- =============================================================================

-- Connect to pluggable database
ALTER SESSION SET CONTAINER = XEPDB1;

-- Drop the old table (data loss acceptable since this is development/testing)
DROP TABLE certificate_duplicates CASCADE CONSTRAINTS;

-- Create new table with PostgreSQL-compatible schema
CREATE TABLE certificate_duplicates (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    certificate_id VARCHAR2(36) NOT NULL,
    upload_id VARCHAR2(36) NOT NULL,
    source_type VARCHAR2(20) NOT NULL,
    source_country VARCHAR2(3),
    source_entry_dn CLOB,
    source_file_name VARCHAR2(255),
    detected_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT fk_cert_dup_cert FOREIGN KEY (certificate_id) REFERENCES certificate(id) ON DELETE CASCADE,
    CONSTRAINT fk_cert_dup_upload FOREIGN KEY (upload_id) REFERENCES uploaded_file(id) ON DELETE CASCADE,
    CONSTRAINT uk_cert_dup_unique UNIQUE (certificate_id, upload_id, source_type)
);

-- Create indexes
CREATE INDEX idx_cert_dup_cert_id ON certificate_duplicates(certificate_id);
CREATE INDEX idx_cert_dup_upload_id ON certificate_duplicates(upload_id);
CREATE INDEX idx_cert_dup_detected_at ON certificate_duplicates(detected_at);
CREATE INDEX idx_cert_dup_source_type ON certificate_duplicates(source_type);

COMMIT;
